language: php

php:
    7.0
    
before_install:
    - composer self-update
    
install: travis_retry composer install --prefer-dist

jobs:
    include:
        - stage: Coverage
          script: ./vendor/bin/phpunit
          after_script:
            - wget https://scrutinizer-ci.com/ocular.phar
            - php ocular.phar code-coverage:upload --format=php-clover build/log/clover.xml
          
